
# Use the official PHP image.
# https://hub.docker.com/_/php
FROM php:8.0-apache

# Copy in custom code from the host machine.
WORKDIR /app/

COPY . /app/.

RUN chmod -R 777 /app/admin/images
RUN chmod -R 777 /app/admin/images/pratos
