FROM geerlingguy/php-apache:latest

COPY . /var/www/html/.

RUN chmod -R 777 /var/www/html/images
RUN chmod -R 777 /var/www/html/logo
RUN chmod -R 777 /var/www/html/icons
RUN chmod -R 777 /var/www/html/vendor
RUN chmod -R 777 /var/www/html/admin
RUN chmod -R 777 /var/www/html/admin/images
RUN chmod -R 777 /var/www/html/admin/images/pratos

COPY ./ports.conf /etc/apache2/ports.conf
COPY ./apache.conf /etc/apache2/site-enabled/000-default.conf